package main;

import java.util.EventListener;

import event.AskForOrderEvent;
import event.NewGeneratedOrderEvent;

/**
 * The ControllerListener interface will be implemented by those Controller classes which wants to receive notifications
 * from the View. In particular ControllerListener extends the EventListener interface by offering specific methods
 * to react to the the Events generated by View's interaction with the users.
 * 
 * @author luca
 */
public interface ControllerListener extends EventListener {
	
	void receiveNewOrder(NewGeneratedOrderEvent newGeneratedOrderEvent);
	
	void askForSpecificOrder(AskForOrderEvent askForOrderEvent);
	
}
